[package]
name = "rust-jmap-webmail"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
uuid = { version = "1", features = ["v7"] }
ureq = { version = "2", features = ["json"] }
base64 = "0.22"
